### ISSUE TITLE
Generation of Presigned Voluntary Exit Messages

### ISSUE THREAD

**Issue by LookingForOwls** [stakevrun/db#1]
### Description
Develop backend functionality to securely generate presigned voluntary exit messages for Ethereum validators. This includes verifying user identity through Ethereum wallet signatures and generating the exit message following user requests.

### Objectives
- Securely verify user identity through Ethereum wallet signature verification.
- Generate presigned voluntary exit messages upon verified requests.
- Provide message to frontend via API.

### Requirements
1. **Ethereum Wallet Signature Verification:** Implement a mechanism to verify users by requiring them to sign a message with their Ethereum wallet. This ensures that the request to generate a presigned exit message is authentic.
2. **Presigned Message Generation:** Upon successful verification, generate the `SignedVoluntaryExit` message as requested by the user.
3. **PGP Encryption Support:** If the user provides a PGP public key, encrypt the generated presigned message before making it available to the user.

### Technical Considerations
- Ensure the security of the signature verification process to prevent unauthorized requests.
- Evaluate and possibly integrate with `ethdo` or develop a custom solution for managing the presigned exit messages.

**Comment by xrchz** [comment]
The exit instruction we already support for immediate exit already creates the signed voluntary exit message, and in fact currently it just prints it in our logs (doesn't broadcast).

**Comment by LookingForOwls** [comment]
The remainder of this task can be tracked on the frontend issue.
