### ISSUE TITLE
DB - Specify "from epoch" for setFeeRecipient instructions

### ISSUE THREAD

**Issue by frankmchugh** [stakevrun/db#13]

**Comment by xrchz** [comment]
Current plan, from Discord:
> I think the best solution might be to slightly change the semantics of the Set Fee Recipient instruction so that it has an extra field (or uses a special setting of the address field, like null) to instruct the backend to just "follow the rocket pool fee recipient rules on my behalf, whatever they say"

**Comment by xrchz** [comment]
This is not needed any more, since we're gonna use the null fee recipient = automatically choose correct rocket pool fee recipient approach.
