### ISSUE TITLE
Update bnports path in act.js

### ISSUE THREAD

**Issue by LookingForOwls** [stakevrun/db#18]
This line should be updated to reflect our deployment config which uses `/usr/share/db`, as a relative path or can be set by an ENV var. 

https://github.com/stakevrun/db/blob/da548ddfdc393e18bf01f2acdff86a2799958114/act.js#L24

I believe that this is already relative but please review:
https://github.com/stakevrun/db/blob/da548ddfdc393e18bf01f2acdff86a2799958114/act.js#L113

**Comment by xrchz** [comment]
So relative paths are fine since the config jsons will be placed in the same directory as the script .js files (which are the db repo clone)?

**Comment by LookingForOwls** [comment]
Yes the config json and bnports will be in the same folder as the JS unless you want it somewhere else like `/mnt/crypt`. I am fine with keeping them all in the same dir if you are.

**Comment by LookingForOwls** [comment]
This is complete and in use in our infra setup code.
