### ISSUE TITLE
Store and Manage Automatically Generated Validator Names

### ISSUE THREAD

**Issue by LookingForOwls** [stakevrun/db#2]
#### Description
Implement backend functionality to store and manage the funny or cute names automatically generated for new validators during the creation process. This includes receiving the generated name from the frontend, storing it in the database, and allowing for subsequent edits by the user.

#### Objectives
- Securely store the automatically generated names for validators.
- Provide functionality to update the validator names as per user edits.

#### Requirements
1. **API Endpoint for Name Reception:** Develop an API endpoint to receive and process the generated names for new validators from the frontend.
2. **Database Schema Update:** Update the database schema to include a field for storing the generated validator names, ensuring compatibility with future edits.
3. **Name Edit Functionality:** Implement backend logic to handle requests for editing the names of validators, including validation to prevent improper data storage.
4. **Integration with Frontend:** Ensure seamless communication between the frontend and backend for both storing the initial names and handling any subsequent edits.

#### Design Considerations
- Implement security measures to sanitize and validate names received from the frontend to prevent injection attacks.

#### Technical Considerations
- Consider implementing caching mechanisms for validator names to enhance retrieval performance, especially for frequently accessed validators.

**Comment by xrchz** [comment]
I think this is actually done with that commit, presuming it doesn't have any bugs, except for the frontend integration.

**Comment by LookingForOwls** [comment]
Closing after review.
