### ISSUE TITLE
Verification and Recording of Terms and Conditions Agreement

### ISSUE THREAD

**Issue by LookingForOwls** [stakevrun/db#3]
#### Description
Develop backend functionality to verify the signature of the terms and conditions agreement made with the user's Ethereum wallet during the validator creation process. This includes verifying the authenticity of the signature and recording the agreement in the database.

#### Objectives
- Securely verify the authenticity of the user's agreement to the terms and conditions.
- Record the agreement in a manner that is easily accessible and verifiable for compliance purposes.

#### Requirements
1. **Signature Verification:** Implement logic to verify the signature received from the frontend against the terms and conditions, ensuring the signer is the intended user.
2. **Database Recording:** Upon successful verification, record the agreement in the database, associating it with the user's account and the specific validator creation transaction.
3. **Compliance and Audit Trail:** Store the agreement in a way that supports compliance checks and audits, including timestamping the agreement.

**Comment by xrchz** [comment]
Can I get review on this? I think it's already implemented.

**Comment by LookingForOwls** [comment]
Reviewed and looks good. Just need an ack that this is working on node creation then we can close.

**Comment by xrchz** [comment]
I'm gonna just assume this works actually. Anyway as I understand it what you wanted ack on would be a frontend issue.
